
export const FETCH_NORRIS_STARTED = "FETCH_NORRIS_STARTED";
export const FETCH_NORRIS_SUCCEEDED = "FETCH_NORRIS_SUCCEEDED";
export const FETCH_NORRIS_FAILED = "FETCH_NORRIS_FAILED";

export const FETCH_NORRIS_DETALHE_STARTED = "FETCH_NORRIS_DETALHE_STARTED";
export const FETCH_NORRIS_DETALHE_SUCCEEDED ="FETCH_NORRIS_DETALHE_SUCCEEDED";
export const FETCH_NORRIS_DETALHE_FAILED = "FETCH_NORRIS_DETALHE_FAILED";

